---
version: "3"

services:
  dtrl01:
    image: dtrl01
    build: build
    restart: always
    hostname: dtrl01
    user: mainuser
    ports:
      - "5901:5901" # VNC
      - "6901:6901" # noVNC
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      VNC_PASSWORD: mainuser
