---
version: "3"

services:
  desktainer-rootless:
    image: docker.io/dmotte/desktainer-rootless:latest
    build: build
    restart: always
    hostname: desktainer-rootless
    ports:
      - "5901:5901"
      - "6901:6901"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      VNC_PASSWORD: changeme
