---
name: shellcheck

on:
  push: # All branches and tags

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ShellCheck
        uses: essentialkaos/shellcheck-action@v1
        with:
          files: build/startup.sh
