---
name: shellcheck

on:
  push:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ShellCheck
        uses: essentialkaos/shellcheck-action@v1
        with:
          files: build/startup.sh
