---
name: shellcheck

on:
  push:
    paths:
      - build/startup.sh
      - .github/workflows/shellcheck.yml

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ShellCheck
        uses: essentialkaos/shellcheck-action@v1
        with:
          files: build/startup.sh
